macos_task:
    osx_instance:
        image: mojave-xcode-10.2
        
    env:
        PATH: /usr/local/opt/qt/bin:$PATH

    install_script:
        - brew install qt
    build_script:
        - mkdir build
        - cd build
        - cmake  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_CONFIGURATION_TYPES=$CMAKE_BUILD_TYPE ..
        - make
